name: dio_retry
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # internet connection checking
  connectivity: ^3.0.6
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: